modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Radial/issues" #optional
[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/ctd-radial.json" #optional
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/ctd-radial" #optional
logoFile="ctd-radial.png" #optional
authors="${mod_authors}" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
description='''${mod_description}'''